// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cat-premium/AerialGrid.tsx": () => import("../components/mockups/cat-premium/AerialGrid.tsx"),
  "./components/mockups/cat-premium/DarkLux.tsx": () => import("../components/mockups/cat-premium/DarkLux.tsx")
};
