// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/category-overview/AccordionList.tsx": () => import("../components/mockups/category-overview/AccordionList.tsx"),
  "./components/mockups/category-overview/MagazineGrid.tsx": () => import("../components/mockups/category-overview/MagazineGrid.tsx"),
  "./components/mockups/category-overview/SidebarNav.tsx": () => import("../components/mockups/category-overview/SidebarNav.tsx")
};
